= Le pôle 1 à la mer !

Qui a dit : c’est ce qu’on murmure dans les pôles 2 et 3 ?

Notre sortie joyeuse et ludique aura lieu lundi 29 et mardi 30 novembre 2021.

== Hotel
https://www.sowell.fr/hotel/le-beach/[Le Beach], https://www.openstreetmap.org/search?query=Quai+Albert+1er%2C+14360+Trouville#map=19/49.36553/0.07735[Quai Albert 1er], 14360 Trouville.

En https://www.google.com/maps/dir/?api=1&travelmode=walking&origin=Gare+de+Deauville&destination=Hôtel+Le+Beach,+Quai+Albert+1er,+14360+Trouville-sur-Mer[vous y rendant depuis la gare], profitez de la vue sur la Touques depuis le Pont des Belges.

== Programme
include::Programme.adoc[]

== Notes
* Nous vous recommandons le train qui arrive depuis Paris à Deauville lundi à 14h45, mais vous n’êtes aucunement obligés de prendre les trains suggérés, vous pouvez arriver plus tard ou partir plus tôt si nécessaire ou plus tard si vous voulez en profiter un peu plus longtemps.
* Vous devez prendre vos billets via le système Notilus.

== Appel à volontaires
Nous voudrions organiser une discussion sur le thème Aide à la Décision et société mardi après-midi. Dites-nous SVP si vous êtes volontaire pour parler 5, 10, 20, 30, 40 minutes sur ce thème en début d’après-midi, que ce soit pour soumettre des questions à discussion, des courtes remarques ou réflexions, par exemple sur ce qui permet ou ce qui bloque d’après vous l’usage concret de l’AD, les bénéfices ou les risques que vous pensez que ses applications entrainent ou pourraient entrainer, etc. (style rump session) ; ou si vous voulez faire part de réflexions plus abouties sur ce thème avec un créneau horaire plus long.

Nous espérons qu’à peu près tout le monde aura au moins un petit quelque chose à partager avec l’assemblée sur ce thème !

